# GLOBAL --------------------------------------------------------------------------
global:
  server_domain: "sunming.peoplematter.localhost:3001"
  client_domain: "sunming.peoplematter.localhost:3000"
  log_level: "debug"

# MODULES -------------------------------------------------------------------------

server:
  host: "0.0.0.0"
  port: 5555
  log_level: "DEV"
  allow_headers: "*"
  allow_methods: "*"
  allow_origins: "*"
  csrf_protection: true
  csrf_secure: false
  csrf_domain: "peoplematter.localhost"
  is_multi_tenant: true
  tenant_identifier: "X-Tenant"
  tenant_identifier_location: "header"

database:
  host: "postgres" #use postgres in docker-compose setup
  port: 5432
  dbname: "postgres"
  user: "postgres"
  password: "password"
  sslmode: "prefer"
  loglevel: "error"
  auto_migrate: true

mailer:
  host: "smtp.gmail.com"
  port: 587
  username: "phyokyawsoe89@gmail.com"
  password: "rzjx eyff upzz wcrx"
  tls: true

transmail:
  sender_email: "team@curate.memorial"
  public_api_key: "230556edd57cad91a4bdc0b56ea7ebfb"
  secret_api_key: "d8b17493bf8b2857d24667dbaa348507"

jwt_auth:
  signing_key: "jwtsecret"
  signing_method: "HS256"
  token_lookup: "cookie:jwt"
  exp_in_hours: 72

jwt_email:
  signing_key: "emailsecret"
  signing_method: "HS256"
  token_lookup: "header:token"
  exp_in_hours: 1

jwt_pw_reset:
  signing_key: "actionsecret"
  signing_method: "HS256"
  token_lookup: "header:token"
  exp_in_hours: 1

# DOMAINS -------------------------------------------------------------------------

auth:
  jwt_auth_scope: "jwt_auth"
  jwt_email_scope: "jwt_email"
  jwt_pw_change_scope: "jwt_pw_change"
  jwt_pw_reset_scope: "jwt_pw_reset"

memorial:
  gitlab_trigger_token: "glptt-8901eb400b6d74388600c219ae2bd614b1186bb0"
