FROM golang:latest

WORKDIR /app

# Set GOBIN environment variable and install Air
ENV GOBIN=/usr/local/bin
RUN go install github.com/cosmtrek/air@latest

# Copy the Go Mod and Sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code into the container
COPY . .

EXPOSE 3001

# Default command (allows hot reloading), can be overridden from docker-compose or docker run
CMD ["air"]